function makeImg(e) { var img = new Image(); img.src = "skins/plox/" + e; return img; }

window.skins.plox = {
	bgColor : "black",
	keycolors : {
		1: [3],
		2: [0,6],
		3: [0,3,6],
		4: [0,2,4,6],
		5: [0,2,3,4,6],
		6: [0,1,2,4,5,6],
		7: [0,1,2,3,4,5,6],
		8: [0,2,4,6,0,2,4,6],
		9: [0,2,4,6,3,0,2,4,6],
		10: [0,1,2,1,0,0,1,2,1,0],
		11: [0,1,2,1,0,2,0,1,2,1,0],
		12: [0,1,2,1,0,1,1,0,1,2,1,0],
		13: [0,1,2,1,0,1,2,1,0,1,2,1,0],
		14: [0,1,2,1,0,1,2,2,1,0,1,2,1,0],
		15: [0,1,0,1,0,1,2,1,2,1,0,1,0,1,0],
		16: [0,1,0,1,0,1,2,1,1,2,1,0,1,0,1,0],
		17: [0,1,1,0,1,2,2,1,2,1,2,2,1,0,1,1,0],
		18: [0,1,1,0,1,2,2,1,0,0,1,2,2,1,0,1,1,0],
	},
	offset: 0.9,
	widthMult: 1,
	keyFront: false,
	keys : [
		{
			true: makeImg("kd_left.png"),
			false: makeImg("k_left.png"),
		},
		{
			true: makeImg("k_downleft.png"),
			false: makeImg("kd_downleft.png"),
		},
		{
			true: makeImg("kd_down.png"),
			false: makeImg("k_down.png"),
		},
		{
			true: makeImg("kd_mid.png"),
			false: makeImg("k_mid.png"),
		},
		{
			true: makeImg("kd_up.png"),
			false: makeImg("k_up.png"),
		},
		{
			true: makeImg("kd_upright.png"),
			false: makeImg("k_upright.png"),
		},
		{
			true: makeImg("kd_right.png"),
			false: makeImg("k_right.png"),
		},
	],
	notes : [
		{
			note: makeImg("left.png"),
			mid: makeImg("base.png"),
			end: makeImg("tail.png"),
		},
		{
			note: makeImg("downleft.png"),
			mid: makeImg("base.png"),
			end: makeImg("tail.png"),
		},
		{
			note: makeImg("down.png"),
			mid: makeImg("base.png"),
			end: makeImg("tail.png"),
		},
		{
			note: makeImg("mid.png"),
			mid: makeImg("base.png"),
			end: makeImg("tail.png"),
		},
		{
			note: makeImg("up.png"),
			mid: makeImg("base.png"),
			end: makeImg("tail.png"),
		},
		{
			note: makeImg("upright.png"),
			mid: makeImg("base.png"),
			end: makeImg("tail.png"),
		},
		{
			note: makeImg("right.png"),
			mid: makeImg("base.png"),
			end: makeImg("tail.png"),
		},
	],
	hitMiss : makeImg("miss.png"),
	hitMax : makeImg("max.png"),
	hit50 : makeImg("50.png"),
	hit100 : makeImg("100.png"),
	hit200 : makeImg("200.png"),
	hit300 : makeImg("300.png"),
	skip : makeImg("skip.png"),
	rankX : makeImg("rank_x.png"),
	rankS : makeImg("rank_s.png"),
	rankA : makeImg("rank_a.png"),
	rankB : makeImg("rank_b.png"),
	rankC : makeImg("rank_c.png"),
	rankD : makeImg("rank_d.png"),
	combo : [
		makeImg("d-0.png"),
		makeImg("d-1.png"),
		makeImg("d-2.png"),
		makeImg("d-3.png"),
		makeImg("d-4.png"),
		makeImg("d-5.png"),
		makeImg("d-6.png"),
		makeImg("d-7.png"),
		makeImg("d-8.png"),
		makeImg("d-9.png"),
	],
}